### ISSUE TITLE
QuickStart: Power Pipelines

### ISSUE THREAD

**Issue by leighatami** [microsoft/power-platform-terraform-quickstarts#27]
As a Terraform user, I want to be able to write a single terraform module that can configure Power Pipelines to manage Power Platform resources the same using tooling/processes that I use to manage Azure resources.

```hcl

resource "powerplatform_environment" "pipelines_env" {

}

resource "powerplatform_application_package" "pipelines_app" {
  environment_id = pipelines_env.id
  package_name= "Power Pipelines"
}

resource "powerplatform_environment" "dev_env" {
  managed = true
}
resource "powerplatform_environment" "uat_env" {
  managed = true
}
resource "powerplatform_environment" "production_env" {
  managed = true
}

```

optional datasources for environment application packages

```[tasklist]
### Tasks
- [x] Create Demo Tenant
- [x] Create 3 Managed Environments
- [ ] Install the pipelines app using microsoft/terraform-provider-power-platform#103
- [x] Create Pipeline
  - [ ] Add security role to user(s)
- [ ] Documentation
- [ ] Examples: terraform files must create Power Platform resources
- [ ] Advanced pipelines and stages
  - [ ] Previous deployment stage required
  - [ ] Pre-deployment step required
- [ ] Test with a sample solution to deploy through pipelines
```

**Comment by mattdot** [comment]
Currently blocked on needing https://github.com/microsoft/terraform-provider-power-platform/issues/278 and https://github.com/microsoft/terraform-provider-power-platform/issues/45
