### ISSUE TITLE
Power Platform Landing Zones Quickstart

### ISSUE THREAD

**Issue by mattdot** [microsoft/power-platform-terraform-quickstarts#32]
As a user, I want an example of setting up [Power Platform Landing Zones reference architecture](https://github.com/microsoft/industry/tree/main/foundations/powerPlatform) using terraform provider
```[tasklist]
### Tasks
- [ ] Implement [this script](https://raw.githubusercontent.com/microsoft/industry/main/foundations/powerPlatform/referenceImplementation/auxiliary/powerPlatform/nsPowerPlatform.ps1) as terraform
- [ ] Documentation
- [x] tenant_settings data source
- [ ] https://github.com/microsoft/terraform-provider-power-platform/issues/90
- [ ] https://github.com/microsoft/terraform-provider-power-platform/issues/44
```
